added sort and filter usecase, except for the sorting based on distan…
HarryC493/CSC207Project pull request #14
Opened 2023-11-19 22:45 UTC by lisazhong13

…ce since we need to discuss whether we want that feature or not, also changed the Restaurant entity to make it easier to get the size of reviews for a restaurant.

2023-11-20 19:57 UTC, HarryC493 commented on src/use_case/sortandfilter/SortAndFilterRestaurantInteractor.java
Missing imports from api.

2023-11-20 19:57 UTC, HarryC493 commented on src/use_case/sortandfilter/SortAndFilterResaturantInputData.java
Missing imports from api.

2023-11-20 19:58 UTC, HarryC493 requested changes
I have pulled this branch to my local computer and I have noticed that the Interactor and Input Data are missing some necessary imports from the api. For example, SearchSortingMethods and SearchPriceLevel from the Interactor. Please modify these so that the code can compile and run.

2023-11-26 02:39 UTC, lisazhong13 commented
> I have pulled this branch to my local computer and I have noticed that the Interactor and Input Data are missing some necessary imports from the api. For example, SearchSortingMethods and SearchPriceLevel from the Interactor. Please modify these so that the code can compile and run.

I have imported all the needing modules and they should be fine now

2023-11-27 21:27 UTC, merged